version: '2'

services:
  web-app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: frontend/web-app
    container_name: web_app
    environment:
      NODE_ENV: "${NODE_ENV}"
      API_HOST: http://api:3000/
      API_HOST_NAME: api
      API_HOST_PORT: 3000
    ports:
      - "8080:80"
    labels:
      container_group: service
    networks:
      - backend_api
networks:
  backend_api:
    external: true
