version: '2'

services:
  web-app:
    container_name: web_app_dev
    environment:
      NODE_ENV: development
      API_HOST: http://localhost:3000/
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ../:/var/lib/app
      # prevent mounting node_modules to avoid cross-platform incompatibilities
      - /var/lib/app/node_modules
    entrypoint: /home/docker/startup.dev.sh
